"""game_url and social links

Revision ID: 1ba207ade0a4
Revises: 24bdebf952e2
Create Date: 2026-06-06 19:53:18.246742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ba207ade0a4'
down_revision = '24bdebf952e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('game_url', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('social_telegram', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('social_youtube', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('social_instagram', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('social_twitter', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('social_custom_url', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('social_custom_label', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_column('social_custom_label')
        batch_op.drop_column('social_custom_url')
        batch_op.drop_column('social_twitter')
        batch_op.drop_column('social_instagram')
        batch_op.drop_column('social_youtube')
        batch_op.drop_column('social_telegram')
        batch_op.drop_column('game_url')

    # ### end Alembic commands ###
