"""genre text, iframe_url, bg_color

Revision ID: 24bdebf952e2
Revises: a5159db9569c
Create Date: 2026-06-06 19:38:09.908059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24bdebf952e2'
down_revision = 'a5159db9569c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bg_color', sa.String(length=7), nullable=True))
        batch_op.alter_column('genre',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.alter_column('genre',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
        batch_op.drop_column('bg_color')

    # ### end Alembic commands ###
