"""add play_history

Revision ID: 316dc7605a3e
Revises: eaf46446ba97
Create Date: 2026-06-06 21:34:00.344600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '316dc7605a3e'
down_revision = 'eaf46446ba97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('play_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('played_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'game_id', name='uq_play_history')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('play_history')
    # ### end Alembic commands ###
